apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: xtdb-benchmark-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  selector:
    matchLabels:
      type: xtdb-benchmark-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 2s
      scrapeTimeout: 1s