# CONFIG FOR RUNNING WITH AZURE INFRA
txLog: !Local
  path: /var/lib/xtdb/log

# txLog: !Kafka
#   bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
#   topicName: !Env XTDB_TOPIC_NAME
#   propertiesMap:
#     compression.type: none
#     security.protocol: SASL_SSL
#     sasl.mechanism: PLAIN
#     sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="";    

# txLog: !Azure
#   namespace: !Env XTDB_AZURE_EVENTHUB_NAMESPACE
#   eventHubName: !Env XTDB_AZURE_EVENTHUB_NAME
#   maxWaitTime: PT5S
#   pollSleepDuration: PT1S
#   userManagedIdentityClientId: !Env XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID

storage: !Remote
  objectStore: !Azure
    storageAccount: !Env XTDB_AZURE_STORAGE_ACCOUNT
    container: !Env XTDB_AZURE_STORAGE_CONTAINER
    serviceBusNamespace: !Env XTDB_AZURE_SERVICE_BUS_NAMESPACE
    serviceBusTopicName: !Env XTDB_AZURE_SERVICE_BUS_TOPIC_NAME
    prefix: "xtdb-object-store"
    userManagedIdentityClientId: !Env XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID
  localDiskCache: !Env XTDB_LOCAL_DISK_CACHE
  maxDiskCachePercentage: 25

metrics: !AzureMonitor
  instrumentationKey: !Env XTDB_AZURE_INSTRUMENTATION_KEY