# CONFIG FOR RUNNING WITH AZURE INFRA
# txLog: !Kafka
#   bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
#   topicName: !Env XTDB_TOPIC_NAME

txLog: !Local
  path: /var/lib/xtdb/log

storage: !Remote
  objectStore: !Azure
    storageAccount: !Env XTDB_AZURE_STORAGE_ACCOUNT
    container: !Env XTDB_AZURE_STORAGE_CONTAINER
    serviceBusNamespace: !Env XTDB_AZURE_SERVICE_BUS_NAMESPACE
    serviceBusTopicName: !Env XTDB_AZURE_SERVICE_BUS_TOPIC_NAME
    prefix: "xtdb-object-store"
  localDiskCache: !Env XTDB_LOCAL_DISK_CACHE

metrics: !AzureMonitor
