name: XTDB CI
run-name: XTDB CI

on:
  push:
    branches-ignore:
      - docs-live

jobs:
  gradle-test:
    name: Gradle Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Pick and set a random system-wide time zone
        run: |
          TZ_LIST=$(timedatectl list-timezones)
          RANDOM_TZ=$(echo "$TZ_LIST" | shuf -n 1)
          echo "Randomly selected time zone: $RANDOM_TZ"

          # Set system time zone
          sudo ln -snf /usr/share/zoneinfo/$RANDOM_TZ /etc/localtime
          echo "$RANDOM_TZ" | sudo tee /etc/timezone
          sudo dpkg-reconfigure -f noninteractive tzdata

      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Print environment info
        run: |
          uname -a
          lsb_release -a || cat /etc/os-release
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "PATH=$PATH"

      - name: Test
        # TODO Remove after tests
        run: ./gradlew :xtdb-http-server:test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: JUnit Test Report
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `gradle-test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
