name: Nightly Benchmark TPC-H

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

permissions:
  id-token: write
  contents: read

jobs:
  benchmark:
    name: Run Nightly Benchmark TPC-H
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Infrastructure
        run: |
          ./modules/bench/cloud/setup-infra.sh azure
        
      - name: Run Benchmark
        run: |
          echo "Dummy step"
        
      - name: Cleanup Infrastructure
        if: always()  # Run cleanup even if previous steps fail
        run: |
          ./modules/bench/cloud/delete-infra.sh azure
